name: Auto Download and Deploy



on:

  schedule:

    - cron: '23 20 * * *' 

  workflow_dispatch: 



permissions:

  contents: write



env:

  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true



jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    

    steps:

      - name: Checkout repository

        uses: actions/checkout@v4

          # 길을 잃지 않도록 main 또는 master 브랜치로 정확히 지정해서 밀어 넣습니다.

          git push origin HEAD:main  git push origin HEAD:master



      - name: Download and Extract

        run: |

          mkdir -p public

          cd public

          wget "https://epgshare01.online/epgshare01/epg_ripper_KR1.xml.gz"

          gunzip epg_ripper_KR1.xml.gz



      - name: Deploy to GitHub Pages

        uses: peaceiris/actions-gh-pages@v4

        with:

          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: ./public

